package com.provectus.kafka.ui.util.enums;

import org.apache.commons.lang3.EnumUtils;
import org.jetbrains.annotations.Nullable;

public enum Permission {

  APPLICATION_ADMIN,

  CLUSTERS_VIEW,

  BROKERS_VIEW,
  BROKERS_EDIT,
  BROKERS_LOGDIRS_VIEW,
  BROKERS_LOGDIRS_EDIT,

  TOPICS_VIEW,
  TOPICS_CREATE,
  TOPICS_EDIT,
  TOPICS_DELETE,

  TOPICS_ANALYSIS_VIEW,
  TOPICS_ANALYSIS_RUN,

  TOPICS_MESSAGES_READ,
  TOPICS_MESSAGES_PRODUCE,
  TOPICS_MESSAGES_DELETE,

  TOPICS_SCHEMA_VIEW,
  TOPICS_CONSUMERGROUPS_VIEW,

  TOPICS_RECREATE,

  CONSUMERGROUPS_VIEW,
  CONSUMERGROUPS_DELETE,
  CONSUMERGROUPS_ALTER_OFFSETS,

  SCHEMAS_VIEW,
  SCHEMAS_CREATE,
  SCHEMAS_DELETE,
  SCHEMAS_EDIT,
  SCHEMAS_MODIFY_COMPATIBILITY,

  CONNECTS_VIEW,

  CONNECTORS_VIEW,
  CONNECTORS_CONFIG_VIEW,
  CONNECTORS_CREATE,
  CONNECTORS_DELETE,
  CONNECTORS_EDIT,
  CONNECTORS_RESTART,

  CONNECTORS_TASKS_VIEW,
  CONNECTORS_TASKS_ALTER,

  KSQL_EXECUTE

  ;

  @Nullable
  public Permission fromString(String name) {
    return EnumUtils.getEnum(Permission.class, name);
  }

}
